services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: ./backend/.env
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
